### ISSUE TITLE
Two things not mentioned for this project

### ISSUE THREAD

**Issue by mediavention** [OPCFoundation/Misc-Tools#5]
1. You need MFC installed to build this project, it is C and C++ MFC, so you need the MFC libs installed to get the required AFXRES.h file. If you do have VS2015 and came from the OPC-UA example to this place you can add MFC to your 2015 Community Visual Studio by going to Programs and Features, Change the VS2015, click the Modify button and add MFC.  
2. To run this you will also need elevated security rights on you machine to run or debug it. 

Finally the link in  the readme file points you off to a bunch of code, not a compiled version of this application.

**Comment by randy-armstrong** [comment]
1) The project has the 'Use Standard Windows Libraries' flag set which means it does NOT need the MFC libraries. That said, it uses Win32 features for embedding resources which is why afxres is included. I did no realize that this is classified as an 'MFC feature' even though the MFC libraries are not used. Will update the readme.

2) The readme has a link to the OPC-F website where you can download a binary. OPC-F policy does not allow the distribution of pre-built EXEs/DLLs in GIT.

**Comment by astrowalker** [comment]
@mediavention , many thanks!

@SparhawkSoftware , maybe I am missing something, but the link exists -- true -- however it leads to page where there are no binaries for certificate generator.

**Comment by randy-armstrong** [comment]
You to download the .NET Samples. They include a binary. It is not distributed separately.

**Comment by foerbsn** [comment]
Am I wrong or is the bin-file missing? I can't find it anywhere.

**Comment by astrowalker** [comment]
@foerbsn , you mean you downloaded and looked into .Net samples?

**Comment by foerbsn** [comment]
Yes, I downloaded
- Misc-Tools
- opc-ua-1.02-.net-stackandsamples
- UA-.NET-.1.03.342

There is no bin-file (except Random.bin) in there.

**Comment by astrowalker** [comment]
Try this one: https://opcfoundation.org/developer-tools/developer-kits-unified-architecture/sample-applications/ (luckily I had this address in documentation :-) )

**Comment by foerbsn** [comment]
That worked, thanks a lot!
